### ISSUE TITLE
KeyError: 'display_freq'

### ISSUE THREAD

**Issue by kilik128** [holy-crusader-py/wombopy#5]
Prompt: love    Style: 3
Starting...
Google identification sign up.
  => idToken got.
Google identification look up.
  => localId got.
Identification done!
Status: pending
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Lib\site-packages\wombopy\__main__.py", line 9, in <module>
    main()
  File "C:\Python311\Lib\site-packages\wombopy\__main__.py", line 5, in main
    cli.app(prog_name=__app_name__)
  File "C:\Python311\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wombopy\cli.py", line 37, in run
    img_uri = create(res["id_token"], prompt, style)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wombopy\core\generation.py", line 63, in create
    display_freq = r.json()["input_spec"]["display_freq"] / 10
                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'display_freq'

**Comment by holy-crusader-py** [comment]
Which version of wombopy do you use ?
